// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/Serendipity565/gora/internal/app"
	"github.com/Serendipity565/gora/internal/config"
	"github.com/Serendipity565/gora/internal/ioc"
	middleware2 "github.com/Serendipity565/gora/internal/middleware"
	"github.com/Serendipity565/gora/internal/server/middleware"
)

// Injectors from wire.go:

// initInfra 装配运行 Gora 所需的基础设施依赖（工具注册表、MySQL、Redis、Logger、JWT、
// Middleware Bundle 等）。
//
// 与 main.go 同包（kratos 风格）：cmd/gora/main.go 直接调用，再把 *app.Infra 交给 app.Run。
// 修改任何 ProviderSet 后必须执行 `make wire` 重新生成 cmd/gora/wire_gen.go。
//
// 返回的 cleanup 会按 wire 生成的反序依次释放底层资源；调用方应在拿到后立即 defer。
func initInfra(ctx context.Context, cfg config.Config) (*app.Infra, func(), error) {
	registry, err := ioc.NewToolRegistry()
	if err != nil {
		return nil, nil, err
	}
	databaseStore, cleanup, err := ioc.NewMySQL(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	activeMemoryCache, cleanup2, err := ioc.NewRedis(ctx, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger, cleanup3, err := ioc.NewLogger(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jwt := ioc.NewJWT(cfg)
	handlerFunc := middleware.NewCorsHandler()
	logConfig := middleware.ProvideLogConfig(cfg)
	loggerMiddleware := middleware2.NewLoggerMiddleware(logger, logConfig)
	v := middleware.ProvideBasicAuthAccounts(cfg)
	basicAuthMiddleware := middleware2.NewBasicAuthMiddleware(v)
	authMiddleware := middleware2.NewAuthMiddleware(jwt)
	limiterConfig := middleware.ProvideLimiterConfig(cfg)
	client, cleanup4, err := ioc.NewRedisClient(ctx, cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	limitMiddleware := middleware2.NewLimitMiddleware(limiterConfig, client)
	prometheusMiddleware := middleware.NewPrometheusMiddleware()
	bundle := middleware.NewBundle(handlerFunc, loggerMiddleware, basicAuthMiddleware, authMiddleware, limitMiddleware, prometheusMiddleware)
	infra := &app.Infra{
		Registry:    registry,
		DB:          databaseStore,
		Cache:       activeMemoryCache,
		Logger:      logger,
		JWT:         jwt,
		Middlewares: bundle,
	}
	return infra, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
