// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"context"
	"github.com/Serendipity565/gora/internal/app"
	"github.com/Serendipity565/gora/internal/config"
	"github.com/Serendipity565/gora/internal/ioc"
)

// Injectors from wire.go:

// InitInfra 装配运行 Gora 所需的基础设施依赖（工具注册表、MySQL、Redis）。
//
// 返回的 cleanup 会按 wire 生成的反序依次释放底层资源；调用方应在错误处理与正常退出
// 时都执行 cleanup（典型用法：拿到后立刻 defer cleanup()）。
func InitInfra(ctx context.Context, cfg config.Config) (*app.Infra, func(), error) {
	registry, err := ioc.NewToolRegistry()
	if err != nil {
		return nil, nil, err
	}
	databaseStore, cleanup, err := ioc.NewMySQL(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	activeMemoryCache, cleanup2, err := ioc.NewRedis(ctx, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	infra := &app.Infra{
		Registry: registry,
		DB:       databaseStore,
		Cache:    activeMemoryCache,
	}
	return infra, func() {
		cleanup2()
		cleanup()
	}, nil
}
